fix: imported horizontal alignment from outline elements into the con…
phase2/outline pull request #105
Opened 2021-08-27 00:20 UTC by tomsshow

…tainer config to avoid namespace issue

<a href="https://gitpod.io/#https://github.com/phase2/outline/pull/105"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-09-03 22:33 UTC, madhaze requested changes

2021-09-03 22:33 UTC, madhaze commented on src/components/base/outline-container/config.ts
> +let HORIZONTAL_ALIGNMENT = ALL_HORIZONTAL_ALIGNMENT;
@tomsshow can you update this to `const` as per the linting issue.

2021-10-20 13:17 UTC, himerus requested changes
Please follow the instructions in #90. 

@tomsshow This approach needs to be updated.

2021-10-20 20:27 UTC, himerus commented
Closing in favor of #133 That approach fixes the referenced issue appropriately.

2021-10-20 20:27 UTC, closed without merging