Upgrade SVGO to v2, because v1 is deprecated
phase2/outline pull request #116
Opened 2021-10-06 19:49 UTC by shaal

2021-10-06 19:50 UTC, grshane approved these changes

2021-10-06 19:55 UTC, LeeMellon approved these changes

2021-10-07 14:41 UTC, himerus requested changes
Please update this in a direct branch from Outline instead of the fork to ensure pipelines pass. I will have to investigate later why Chromatic builds fail if it's done in a forked repo.

2021-10-08 02:47 UTC, shaal commented
I created https://github.com/phase2/outline/pull/123

2021-10-08 02:47 UTC, closed without merging