Feature/outline icon update
phase2/outline pull request #118
Opened 2021-10-06 20:45 UTC by LeeMellon

Update to match @mabry1985 work on internal project

<img width="815" alt="Cursor_and_Branding___Graphics___Icons_-_Icons_⋅_Storybook" src="https://user-images.githubusercontent.com/11083407/136280449-ea7d0635-bdf9-459f-8d0a-fe312763822b.png">

<a href="https://gitpod.io/#https://github.com/phase2/outline/pull/118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-10-07 14:40 UTC, himerus requested changes

2021-10-07 14:40 UTC, himerus commented on src/components/base/outline-accordion/outline-accordion.css
> +  @apply text-blue-700 text-lg;
Let's use the `demo` palette here as well. So maybe `text-demo-darkBlue`. 
We need to expand the `demo` palette to have some more colors for that out of the box styling.

2021-10-20 13:58 UTC, himerus commented on src/components/base/outline-accordion/outline-accordion.css
> +  @apply text-blue-700 text-lg;
Pushed fix.

2021-10-20 15:37 UTC, damontgomery commented
Cool. :) Where did the icons come from / are they free to use on any project / have rules around usage?

We are using Google Material Icons on another internal project and have adapted and earlier version of this work to handle those icons.

2021-10-20 17:02 UTC, merged