Feature/outline image slider
phase2/outline pull request #137
Opened 2021-10-27 23:51 UTC by mabry1985

- Adds Splidejs Carousel library
- Adds `outline-image-slider`
- Closes [Issue 107](https://github.com/phase2/outline/issues/107)

Mobile: 
![Screen Shot 2021-10-27 at 4 49 35 PM](https://user-images.githubusercontent.com/31560031/139163377-d4fd2ce8-49ac-49c9-824f-00f1c74e3399.png)

Full Viewport: 
![Screen Shot 2021-10-27 at 4 51 14 PM](https://user-images.githubusercontent.com/31560031/139163428-0c513988-5548-4877-94a8-288d79e1daf9.png)

<a href="https://gitpod.io/#https://github.com/phase2/outline/pull/137"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2021-10-27 23:52 UTC, mabry1985 commented on src/components/base/outline-image-gallery/outline-image-gallery.css
> +@import '@splidejs/splide/dist/css/splide-core.min.css';
@shaal Here is how I ended up importing the css from node modules

2021-10-28 00:07 UTC, shaal commented on src/components/base/outline-image-gallery/outline-image-gallery.css
> +@import '@splidejs/splide/dist/css/splide-core.min.css';
@mabry1985 nice!!!

2021-10-28 00:32 UTC, grshane approved these changes

2021-10-28 00:32 UTC, grshane commented on src/components/base/outline-image-slider/outline-image-slider.css
> +  @apply bg-brand-primary absolute flex justify-center bottom-0 left-0 z-40 w-full;
For extensibility would it make sense to define a css var for the arrow color?

2021-11-18 21:13 UTC, mabry1985 commented on src/components/base/outline-image-slider/outline-image-slider.css
> +  @apply bg-brand-primary absolute flex justify-center bottom-0 left-0 z-40 w-full;
Sorry I missed this comment when it was first added. Yeah I think that makes sense, there would be more follow up tickets needed to make it a little more flexible for sure.

2021-11-18 22:01 UTC, damontgomery reviewed
Thanks, @mabry1985!

I used this as a model for an internal project and it worked well.

I can understand the code.

For general purpose use, I'm not sure what to make of this type of component. I had to modify the Splide configuration and CSS a lot for our use on that project since the carousel is quite different. So, it's a nice starting point, but I can't imagine a project using it as-is.

I also took a different approach where I copied the slides into the shadow DOM instead of using dynamically created slots per slide. That to me is a little simpler, but this is clear enough and works well.

Thanks again and happy to talk through that other example if it's helpful.

2021-11-18 22:01 UTC, damontgomery commented on src/components/base/outline-image-slider/outline-image-slider.css
> +}
Splide has a configuration to disable pagination. We're using this on an internal project if you want to use that. Not necessary.

2021-11-18 22:01 UTC, damontgomery commented on src/components/base/outline-image-slider/outline-image-slider.css
> +.sr-only {
minor: Can we call this `screen-reader-only`?

2021-11-19 16:06 UTC, mabry1985 commented on src/components/base/outline-image-slider/outline-image-slider.css
> +}
Yeah I'm aware of the Splide configuration there, I believe this was how I saw it done in the accessible boilerplate to create your own buttons while still using the functionality of the pagination. I think it's probably redundant though. Good catch.

2021-11-19 16:07 UTC, mabry1985 commented on src/components/base/outline-image-slider/outline-image-slider.css
> +.sr-only {
sr-only is what I've seen it called in several places, but it's no matter to me what we call it here.

2021-11-19 16:10 UTC, mabry1985 commented
@damontgomery thanks for taking a look and the thoughtful pr. I'd be happy to take a look at your iteration on this. I was just looking to back port the component from SMC and we could add any follow up tickets needed to improve it. We discussed several weeks ago about getting stuff in quick and dirty and improving when there is time. I don't know if this means leaving these components in the PR queue until there is time to update them or pulling them into a branch of their own. @himerus what are your thoughts there?

2021-12-08 03:24 UTC, himerus requested changes
@mabry1985 Can you look at https://github.com/phase2/outline/security/dependabot/yarn.lock/prismjs/open and see if we can bump the version of splide enough to avoid this error?

2021-12-08 03:28 UTC, himerus approved these changes

2021-12-16 18:45 UTC, himerus commented
Awaiting fix for caption and navigation positioning.

2022-02-12 15:38 UTC, himerus commented
I plan to pick this one up likely quite soon. We used this component as a starting point for another project, and I have some updates to pull in as well as the adjustments that may need to be pulled back in from the original work.

2022-02-15 18:16 UTC, merged