chore: add prettier-tailwind plugin and format all css files
phase2/outline pull request #217
Opened 2022-02-09 21:46 UTC by grshane

2022-02-09 21:53 UTC, shaal commented
This PR is a great example of why using prettier with Tailwind makes no sense.

Take a look at all the files that changed. How does that help?

I would love to see prettier with regular CSS, when each css rule has its own line.
When you change margin for example, you would see the update just in margin.

2022-02-10 17:02 UTC, sarahp approved these changes
Looks good to me!

2022-02-10 17:35 UTC, himerus requested changes
I'm curious, where do we define that we are USING the plugin? Is there no change to the tailwind config? I apologize, I didn't read the article that talked about the new feature.

2022-02-10 17:35 UTC, himerus commented on src/components/base/outline-card/outline-card.ts
> +    console.log('warn');
What's up here?

2022-02-10 17:54 UTC, grshane commented
> This plugin follows Prettier’s autoloading convention, so as long as you’ve got Prettier set up in your project, it’ll start working automatically as soon as it’s installed.

2022-02-12 14:05 UTC, himerus approved these changes

2022-02-12 14:10 UTC, himerus commented
![image](https://user-images.githubusercontent.com/21905/153714670-217a6d8a-e963-4573-8224-2303239a60c8.png)

As a note, if you use multiple `@apply` directives to separate concerns as shown above, this plugin will only format them PER line. 🔥 🔥 🔥

2022-02-12 14:36 UTC, himerus commented
> This PR is a great example of why using prettier with Tailwind makes no sense.
> 
> Take a look at all the files that changed. How does that help?
> 
> I would love to see prettier with regular CSS, when each css rule has its own line. When you change margin for example, you would see the update just in margin.

This helps by providing consistency with our current tools. That is all.

2022-02-12 15:03 UTC, merged